use std::{collections::HashMap, sync::LazyLock};

use crate::schema::{FrameworkName, Mode, Registry, RegistryEntry, RegistryItemType, RegistryItemFile, RegistryItemTailwind, RegistryItemTailwindConfig};

/// Creates a complete registry entry for a UI component with enhanced metadata
fn create_ui_component(
    name: &str,
    description: &str,
    category: &str,
    dependencies: Vec<&str>,
) -> RegistryEntry {
    create_ui_component_with_metadata(
        name,
        description,
        category,
        None,
        dependencies,
        None,
        None,
        None,
    )
}

/// Creates a complete registry entry for a UI component with full metadata control
fn create_ui_component_with_metadata(
    name: &str,
    description: &str,
    category: &str,
    subcategory: Option<&str>,
    dependencies: Vec<&str>,
    registry_dependencies: Option<Vec<&str>>,
    css_vars: Option<HashMap<Mode, HashMap<String, String>>>,
    tailwind_plugins: Option<Vec<&str>>,
) -> RegistryEntry {
    let tailwind = if let Some(plugins) = tailwind_plugins {
        Some(RegistryItemTailwind {
            config: RegistryItemTailwindConfig {
                content: None,
                plugins: Some(plugins.into_iter().map(|s| s.into()).collect()),
            },
        })
    } else {
        None
    };

    RegistryEntry {
        name: name.into(),
        r#type: RegistryItemType::Ui,
        description: Some(description.into()),
        dependencies: Some(dependencies.into_iter().map(|s| s.into()).collect()),
        dev_dependencies: Some(vec!["wasm-bindgen-test".into()]),
        registry_dependencies: registry_dependencies.map(|deps| deps.into_iter().map(|s| s.into()).collect()),
        files: Some(vec![
            RegistryItemFile {
                path: format!("ui/{}.rs", name),
                content: None,
                r#type: RegistryItemType::Ui,
                target: None,
            }
        ]),
        tailwind,
        css_vars,
        source: Some(format!("https://ui.shadcn.com/docs/components/{}", name.replace("-", "").replace("navigationmenu", "navigation-menu").replace("inputotp", "input-otp").replace("datepicker", "date-picker").replace("hovercard", "hover-card").replace("radiogroup", "radio-group").replace("scrollarea", "scroll-area").replace("aspectratio", "aspect-ratio"))),
        category: Some(category.into()),
        subcategory: subcategory.map(|s| s.into()),
        chunks: None,
        docs: Some(format!("https://shadcn-ui.rustforweb.org/components/{}.html", name.replace("-", ""))),
    }
}

/// Helper to create CSS variables map for themable components
fn create_css_vars(variables: Vec<(&str, &str)>) -> HashMap<Mode, HashMap<String, String>> {
    let mut mode_map = HashMap::new();
    let mut var_map = HashMap::new();
    for (key, value) in variables {
        var_map.insert(key.to_string(), value.to_string());
    }
    mode_map.insert(Mode::Light, var_map);
    mode_map
}

/// Complete component registry for all shadcn/ui components with comprehensive metadata
fn create_complete_registry() -> Registry {
    vec![
        // ========================================================================
        // FORM & INPUT COMPONENTS (13 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "button",
            "Displays a button or a component that looks like a button. Supports multiple variants including default, destructive, outline, secondary, ghost, and link. Includes icon support and loading states.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--button-background", "hsl(var(--primary))"),
                ("--button-foreground", "hsl(var(--primary-foreground))"),
                ("--button-hover-background", "hsl(var(--primary)/0.9)"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "checkbox",
            "A control that allows the user to toggle between checked and not checked. Supports indeterminate state and custom styling.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--checkbox-background", "hsl(var(--primary))"),
                ("--checkbox-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "radio-group",
            "A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time. Ideal for selecting from a small set of mutually exclusive options.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--radio-background", "hsl(var(--primary))"),
                ("--radio-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "select",
            "Displays a list of options for the user to pick from—triggered by a button. Supports single selection, keyboard navigation, and customizable triggers.",
            "forms",
            Some("dropdown"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "combobox",
            "Autocomplete input and command palette with a list of suggestions. Combines an input with a dropdown menu for filtering and selecting from large datasets.",
            "forms",
            Some("autocomplete"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["command", "popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "form",
            "Building blocks for creating accessible forms with validation. Provides form context, field components, and integration with validation libraries.",
            "forms",
            Some("container"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["label", "input", "checkbox", "radio-group"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "input",
            "Displays a form input field or a component that looks like an input field. Supports various types including text, email, password, number, and file inputs.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--input-background", "hsl(var(--background))"),
                ("--input-foreground", "hsl(var(--foreground))"),
                ("--input-border", "hsl(var(--input))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "label",
            "Renders an accessible label associated with controls. Essential for form accessibility and can be linked to inputs via HTML htmlFor attribute.",
            "forms",
            Some("container"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "textarea",
            "Displays a form textarea or a component that looks like a textarea. Provides multi-line text input with auto-resize support.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "slider",
            "An input where the user selects a value from within a given range. Supports single and multiple thumbs, vertical orientation, and custom styling.",
            "forms",
            Some("range"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--slider-background", "hsl(var(--primary))"),
                ("--slider-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "switch",
            "A control that allows the user to toggle between checked and not checked. Similar to a checkbox but with a distinct visual design optimized for toggle actions.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--switch-background", "hsl(var(--input))"),
                ("switch-foreground", "hsl(var(--background))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "toggle",
            "A two-state button that can be either on or off. Can be used individually or in groups for selecting multiple options.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--toggle-background", "hsl(var(--primary))"),
                ("--toggle-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "toggle-group",
            "A set of two-state buttons that can be toggled on or off. Useful for segmented controls and option groups where single or multiple selection is needed.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["toggle"]),
            None,
            None,
        ),

        // ========================================================================
        // NAVIGATION COMPONENTS (7 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "navigation-menu",
            "A collection of links for navigating websites. Displays a hierarchical menu with support for dropdowns, icons, and keyboard navigation.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "menubar",
            "A visually persistent menu common in desktop applications. Displays menu items in a horizontal bar with dropdown submenus.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["dropdown-menu"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "tabs",
            "A set of layered sections of content—known as tab panels—that are displayed one at a time. Supports keyboard navigation and customizable tab lists.",
            "navigation",
            Some("tabs"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--tabs-background", "hsl(var(--background))"),
                ("--tabs-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "breadcrumb",
            "Displays the path to the current resource using a hierarchy of links. Essential for navigation in deep page hierarchies.",
            "navigation",
            Some("breadcrumbs"),
            vec!["tailwind_fuse"],
            Some(vec!["separator"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "pagination",
            "Pagination with page navigation, next and previous links. Supports customizable page counts, ellipsis for large page sets, and size variants.",
            "navigation",
            Some("pagination"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "command",
            "Fast, composable, unstyled command menu. Ideal for command palettes, searchable lists, and autocomplete functionality with keyboard navigation.",
            "navigation",
            Some("command"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "context-menu",
            "Displays a menu to the user—such as a set of actions or functions—triggered by right-click or long-press on an element.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),

        // ========================================================================
        // OVERLAY COMPONENTS (8 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "dialog",
            "A window overlaid on either the primary window or another dialog window. Supports modal and non-modal modes with customizable animations.",
            "overlay",
            Some("dialogs"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--dialog-background", "hsl(var(--background))"),
                ("--dialog-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "alert-dialog",
            "A modal dialog that interrupts the user with important content and expects a response. Ideal for confirmations and critical alerts.",
            "overlay",
            Some("dialogs"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            Some(create_css_vars(vec![
                ("--alert-dialog-background", "hsl(var(--background))"),
                ("--alert-dialog-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "sheet",
            "Extends the Dialog component to display content that complements the main content of the screen. Slides in from edges with customizable animations.",
            "overlay",
            Some("drawers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "drawer",
            "A panel that slides out from the edge of the screen. Similar to Sheet but optimized for mobile and touch interactions.",
            "overlay",
            Some("drawers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "dropdown-menu",
            "Displays a menu to the user—such as a set of actions or functions—triggered by a button. Supports nested submenus and keyboard navigation.",
            "overlay",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "popover",
            "Displays rich content in a portal, triggered by a button. Highly flexible overlay component for custom content and interactions.",
            "overlay",
            Some("popovers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--popover-background", "hsl(var(--popover))"),
                ("--popover-foreground", "hsl(var(--popover-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "tooltip",
            "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. Supports custom positioning and delays.",
            "overlay",
            Some("tooltips"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "toast",
            "A succinct message that is displayed temporarily. Supports multiple positions, variants (default, destructive, action), and auto-dismissal.",
            "overlay",
            Some("notifications"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--toast-background", "hsl(var(--background))"),
                ("--toast-foreground", "hsl(var(--foreground))"),
                ("--toast-border", "hsl(var(--border))"),
            ])),
            None,
        ),

        // ========================================================================
        // LAYOUT COMPONENTS (7 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "accordion",
            "A vertically stacked set of interactive headings that each reveal a section of content. Supports multiple open items and collapsible all behavior.",
            "layout",
            Some("disclosure"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "collapsible",
            "An interactive component which can be expanded/collapsed. Foundation component for Accordion and other disclosure widgets.",
            "layout",
            Some("disclosure"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "resizable",
            "Accessible resizable panel groups and layouts with keyboard support. Enables creating resizable split-pane layouts with persistence.",
            "layout",
            Some("panels"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "scroll-area",
            "Augments native scroll functionality for custom, cross-browser styling. Provides consistent scrollbar appearance across platforms.",
            "layout",
            Some("scrolling"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "separator",
            "Visually or semantically separates content. Renders a horizontal or vertical divider with customizable orientation and styling.",
            "layout",
            Some("dividers"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "sidebar",
            "Composable, themeable, multi-level sidebar navigation component. Supports collapsible sections, nested menus, and mobile responsiveness.",
            "layout",
            Some("sidebars"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["collapsible", "separator"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "aspect-ratio",
            "Displays content within a desired ratio. Ideal for maintaining consistent aspect ratios for images, videos, and embeddable content.",
            "layout",
            Some("containers"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),

        // ========================================================================
        // DISPLAY COMPONENTS (8 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "alert",
            "Displays a callout for user attention. Supports variants including default, destructive, and warning. Ideal for notifications and warnings.",
            "display",
            Some("alerts"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--alert-background", "hsl(var(--background))"),
                ("--alert-foreground", "hsl(var(--foreground))"),
                ("--alert-border", "hsl(var(--border))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "avatar",
            "An image element with a fallback for representing the user. Supports images, initials, and loading states with multiple sizes.",
            "display",
            Some("user"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "badge",
            "Displays a badge or a component that looks like a badge. Ideal for status indicators, counts, and labels with multiple variants.",
            "display",
            Some("labels"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--badge-background", "hsl(var(--primary))"),
                ("--badge-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "card",
            "Displays a card with header, content, and footer. A versatile container component for grouping related content and actions.",
            "display",
            Some("containers"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--card-background", "hsl(var(--card))"),
                ("--card-foreground", "hsl(var(--card-foreground))"),
                ("--card-border", "hsl(var(--border))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "calendar",
            "A date field component that allows users to enter and edit dates. Supports single date, date range, and multiple date selection modes.",
            "display",
            Some("dates"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--calendar-background", "hsl(var(--background))"),
                ("--calendar-foreground", "hsl(var(--foreground))"),
                ("--calendar-primary", "hsl(var(--primary))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "progress",
            "Displays an indicator showing the completion progress of a task. Supports determinate and indeterminate states with customizable styling.",
            "display",
            Some("feedback"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--progress-background", "hsl(var(--primary))"),
                ("--progress-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "skeleton",
            "Use to show a placeholder while content is loading. Provides a visual placeholder that matches the structure of expected content.",
            "display",
            Some("feedback"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "table",
            "A responsive table component with header, body, and footer. Supports sorting, selection, and custom styling with consistent borders.",
            "display",
            Some("data"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--table-background", "hsl(var(--background))"),
                ("--table-foreground", "hsl(var(--foreground))"),
                ("--table-border", "hsl(var(--border))"),
                ("--table-header-background", "hsl(var(--muted))"),
            ])),
            None,
        ),

        // ========================================================================
        // ADVANCED COMPONENTS (7 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "carousel",
            "A carousel with motion and swipe built using Embla. Supports autoplay, loop, draggable, and custom navigation with multiple slides per view.",
            "advanced",
            Some("media"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            None,
            Some(vec!["embla-carousel-react"]),
        ),
        create_ui_component_with_metadata(
            "date-picker",
            "A date picker component with range and multiple selection. Combines calendar functionality with input field for comprehensive date selection.",
            "advanced",
            Some("dates"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["calendar", "popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "hover-card",
            "For sighted users to preview content available behind a link. Displays rich content on hover with customizable positioning and delay.",
            "advanced",
            Some("overlays"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "input-otp",
            "Accessible one-time password component with copy paste functionality. Ideal for 2FA codes and verification inputs with spinner support.",
            "advanced",
            Some("input"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "utils",
            "Utility functions and helpers for the component library. Includes class name merging, cn utility, and common helper functions.",
            "advanced",
            Some("utilities"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),

        // ========================================================================
        // NOT YET IMPLEMENTED (4 total) - Available in Dioxus/Planned
        // ========================================================================
        create_ui_component_with_metadata(
            "chart",
            "Recharts components built using Recharts and designed to work seamlessly with shadcn/ui. Provides beautiful, responsive chart components.",
            "advanced",
            Some("data-visualization"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            Some(vec!["recharts"]),
        ),
        create_ui_component_with_metadata(
            "data-table",
            "Powerful table and datagrids built using TanStack Table. Features sorting, filtering, pagination, and row selection with column resizing.",
            "advanced",
            Some("data"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["table", "button", "checkbox", "input", "dropdown-menu"]),
            None,
            Some(vec!["@tanstack/react-table"]),
        ),
        create_ui_component_with_metadata(
            "sonner",
            "An opinionated toast component with beautiful animations. Supports multiple types, promises, and custom styling with stack management.",
            "advanced",
            Some("notifications"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            Some(vec!["sonner"]),
        ),
        create_ui_component_with_metadata(
            "typography",
            "Styles for headings, paragraphs, lists, and other text elements. Provides consistent typography with customizable variants and scales.",
            "advanced",
            Some("text"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--typography-h1", "2.5rem"),
                ("--typography-h2", "2rem"),
                ("--typography-h3", "1.75rem"),
                ("--typography-h4", "1.5rem"),
            ])),
            None,
        ),
    ]
}

/// Creates the complete Leptos registry with comprehensive metadata for all implemented components
/// This registry reflects the actual state of Leptos implementation (49 components)
fn create_leptos_registry() -> Registry {
    vec![
        // ========================================================================
        // FORM & INPUT COMPONENTS (13 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "button",
            "Displays a button or a component that looks like a button. Supports multiple variants including default, destructive, outline, secondary, ghost, and link. Includes icon support and loading states.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--button-background", "hsl(var(--primary))"),
                ("--button-foreground", "hsl(var(--primary-foreground))"),
                ("--button-hover-background", "hsl(var(--primary)/0.9)"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "checkbox",
            "A control that allows the user to toggle between checked and not checked. Supports indeterminate state and custom styling.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--checkbox-background", "hsl(var(--primary))"),
                ("--checkbox-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "radio-group",
            "A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time. Ideal for selecting from a small set of mutually exclusive options.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--radio-background", "hsl(var(--primary))"),
                ("--radio-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "select",
            "Displays a list of options for the user to pick from—triggered by a button. Supports single selection, keyboard navigation, and customizable triggers.",
            "forms",
            Some("dropdown"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "combobox",
            "Autocomplete input and command palette with a list of suggestions. Combines an input with a dropdown menu for filtering and selecting from large datasets.",
            "forms",
            Some("autocomplete"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["command", "popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "form",
            "Building blocks for creating accessible forms with validation. Provides form context, field components, and integration with validation libraries.",
            "forms",
            Some("container"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["label", "input", "checkbox", "radio-group"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "input",
            "Displays a form input field or a component that looks like an input field. Supports various types including text, email, password, number, and file inputs.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--input-background", "hsl(var(--background))"),
                ("--input-foreground", "hsl(var(--foreground))"),
                ("--input-border", "hsl(var(--input))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "label",
            "Renders an accessible label associated with controls. Essential for form accessibility and can be linked to inputs via HTML htmlFor attribute.",
            "forms",
            Some("container"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "textarea",
            "Displays a form textarea or a component that looks like a textarea. Provides multi-line text input with auto-resize support.",
            "forms",
            Some("basic-input"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "slider",
            "An input where the user selects a value from within a given range. Supports single and multiple thumbs, vertical orientation, and custom styling.",
            "forms",
            Some("range"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--slider-background", "hsl(var(--primary))"),
                ("--slider-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "switch",
            "A control that allows the user to toggle between checked and not checked. Similar to a checkbox but with a distinct visual design optimized for toggle actions.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--switch-background", "hsl(var(--input))"),
                ("switch-foreground", "hsl(var(--background))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "toggle",
            "A two-state button that can be either on or off. Can be used individually or in groups for selecting multiple options.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--toggle-background", "hsl(var(--primary))"),
                ("--toggle-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "toggle-group",
            "A set of two-state buttons that can be toggled on or off. Useful for segmented controls and option groups where single or multiple selection is needed.",
            "forms",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["toggle"]),
            None,
            None,
        ),

        // ========================================================================
        // NAVIGATION COMPONENTS (7 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "navigation-menu",
            "A collection of links for navigating websites. Displays a hierarchical menu with support for dropdowns, icons, and keyboard navigation.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "menubar",
            "A visually persistent menu common in desktop applications. Displays menu items in a horizontal bar with dropdown submenus.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["dropdown-menu"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "tabs",
            "A set of layered sections of content—known as tab panels—that are displayed one at a time. Supports keyboard navigation and customizable tab lists.",
            "navigation",
            Some("tabs"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--tabs-background", "hsl(var(--background))"),
                ("--tabs-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "breadcrumb",
            "Displays the path to the current resource using a hierarchy of links. Essential for navigation in deep page hierarchies.",
            "navigation",
            Some("breadcrumbs"),
            vec!["tailwind_fuse"],
            Some(vec!["separator"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "pagination",
            "Pagination with page navigation, next and previous links. Supports customizable page counts, ellipsis for large page sets, and size variants.",
            "navigation",
            Some("pagination"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "command",
            "Fast, composable, unstyled command menu. Ideal for command palettes, searchable lists, and autocomplete functionality with keyboard navigation.",
            "navigation",
            Some("command"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "context-menu",
            "Displays a menu to the user—such as a set of actions or functions—triggered by right-click or long-press on an element.",
            "navigation",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),

        // ========================================================================
        // OVERLAY COMPONENTS (8 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "dialog",
            "A window overlaid on either the primary window or another dialog window. Supports modal and non-modal modes with customizable animations.",
            "overlay",
            Some("dialogs"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--dialog-background", "hsl(var(--background))"),
                ("--dialog-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "alert-dialog",
            "A modal dialog that interrupts the user with important content and expects a response. Ideal for confirmations and critical alerts.",
            "overlay",
            Some("dialogs"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            Some(create_css_vars(vec![
                ("--alert-dialog-background", "hsl(var(--background))"),
                ("--alert-dialog-foreground", "hsl(var(--foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "sheet",
            "Extends the Dialog component to display content that complements the main content of the screen. Slides in from edges with customizable animations.",
            "overlay",
            Some("drawers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "drawer",
            "A panel that slides out from the edge of the screen. Similar to Sheet but optimized for mobile and touch interactions.",
            "overlay",
            Some("drawers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "dropdown-menu",
            "Displays a menu to the user—such as a set of actions or functions—triggered by a button. Supports nested submenus and keyboard navigation.",
            "overlay",
            Some("menus"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "popover",
            "Displays rich content in a portal, triggered by a button. Highly flexible overlay component for custom content and interactions.",
            "overlay",
            Some("popovers"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--popover-background", "hsl(var(--popover))"),
                ("--popover-foreground", "hsl(var(--popover-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "tooltip",
            "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. Supports custom positioning and delays.",
            "overlay",
            Some("tooltips"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "toast",
            "A succinct message that is displayed temporarily. Supports multiple positions, variants (default, destructive, action), and auto-dismissal.",
            "overlay",
            Some("notifications"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--toast-background", "hsl(var(--background))"),
                ("--toast-foreground", "hsl(var(--foreground))"),
                ("--toast-border", "hsl(var(--border))"),
            ])),
            None,
        ),

        // ========================================================================
        // LAYOUT COMPONENTS (7 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "accordion",
            "A vertically stacked set of interactive headings that each reveal a section of content. Supports multiple open items and collapsible all behavior.",
            "layout",
            Some("disclosure"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "collapsible",
            "An interactive component which can be expanded/collapsed. Foundation component for Accordion and other disclosure widgets.",
            "layout",
            Some("disclosure"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "resizable",
            "Accessible resizable panel groups and layouts with keyboard support. Enables creating resizable split-pane layouts with persistence.",
            "layout",
            Some("panels"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "scroll-area",
            "Augments native scroll functionality for custom, cross-browser styling. Provides consistent scrollbar appearance across platforms.",
            "layout",
            Some("scrolling"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "separator",
            "Visually or semantically separates content. Renders a horizontal or vertical divider with customizable orientation and styling.",
            "layout",
            Some("dividers"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "sidebar",
            "Composable, themeable, multi-level sidebar navigation component. Supports collapsible sections, nested menus, and mobile responsiveness.",
            "layout",
            Some("sidebars"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["collapsible", "separator"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "aspect-ratio",
            "Displays content within a desired ratio. Ideal for maintaining consistent aspect ratios for images, videos, and embeddable content.",
            "layout",
            Some("containers"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),

        // ========================================================================
        // DISPLAY COMPONENTS (8 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "alert",
            "Displays a callout for user attention. Supports variants including default, destructive, and warning. Ideal for notifications and warnings.",
            "display",
            Some("alerts"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--alert-background", "hsl(var(--background))"),
                ("--alert-foreground", "hsl(var(--foreground))"),
                ("--alert-border", "hsl(var(--border))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "avatar",
            "An image element with a fallback for representing the user. Supports images, initials, and loading states with multiple sizes.",
            "display",
            Some("user"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "badge",
            "Displays a badge or a component that looks like a badge. Ideal for status indicators, counts, and labels with multiple variants.",
            "display",
            Some("labels"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--badge-background", "hsl(var(--primary))"),
                ("--badge-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "card",
            "Displays a card with header, content, and footer. A versatile container component for grouping related content and actions.",
            "display",
            Some("containers"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--card-background", "hsl(var(--card))"),
                ("--card-foreground", "hsl(var(--card-foreground))"),
                ("--card-border", "hsl(var(--border))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "calendar",
            "A date field component that allows users to enter and edit dates. Supports single date, date range, and multiple date selection modes.",
            "display",
            Some("dates"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            Some(create_css_vars(vec![
                ("--calendar-background", "hsl(var(--background))"),
                ("--calendar-foreground", "hsl(var(--foreground))"),
                ("--calendar-primary", "hsl(var(--primary))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "progress",
            "Displays an indicator showing the completion progress of a task. Supports determinate and indeterminate states with customizable styling.",
            "display",
            Some("feedback"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--progress-background", "hsl(var(--primary))"),
                ("--progress-foreground", "hsl(var(--primary-foreground))"),
            ])),
            None,
        ),
        create_ui_component_with_metadata(
            "skeleton",
            "Use to show a placeholder while content is loading. Provides a visual placeholder that matches the structure of expected content.",
            "display",
            Some("feedback"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "table",
            "A responsive table component with header, body, and footer. Supports sorting, selection, and custom styling with consistent borders.",
            "display",
            Some("data"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--table-background", "hsl(var(--background))"),
                ("--table-foreground", "hsl(var(--foreground))"),
                ("--table-border", "hsl(var(--border))"),
                ("--table-header-background", "hsl(var(--muted))"),
            ])),
            None,
        ),

        // ========================================================================
        // ADVANCED COMPONENTS (6 total)
        // ========================================================================
        create_ui_component_with_metadata(
            "carousel",
            "A carousel with motion and swipe built using Embla. Supports autoplay, loop, draggable, and custom navigation with multiple slides per view.",
            "advanced",
            Some("media"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["button"]),
            None,
            Some(vec!["embla-carousel-react"]),
        ),
        create_ui_component_with_metadata(
            "date-picker",
            "A date picker component with range and multiple selection. Combines calendar functionality with input field for comprehensive date selection.",
            "advanced",
            Some("dates"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["calendar", "popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "hover-card",
            "For sighted users to preview content available behind a link. Displays rich content on hover with customizable positioning and delay.",
            "advanced",
            Some("overlays"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["popover"]),
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "input-otp",
            "Accessible one-time password component with copy paste functionality. Ideal for 2FA codes and verification inputs with spinner support.",
            "advanced",
            Some("input"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "utils",
            "Utility functions and helpers for the component library. Includes class name merging, cn utility, and common helper functions.",
            "advanced",
            Some("utilities"),
            vec!["tailwind_fuse"],
            None,
            None,
            None,
        ),
        create_ui_component_with_metadata(
            "toggle-group",
            "A set of two-state buttons that can be toggled on or off. Useful for segmented controls and option groups where single or multiple selection is needed.",
            "advanced",
            Some("selection"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["toggle"]),
            None,
            None,
        ),

        // ========================================================================
        // NOT YET IMPLEMENTED IN LEPTOS (4 total) - Available in Dioxus/Planned
        // ========================================================================
        create_ui_component_with_metadata(
            "chart",
            "Recharts components built using Recharts and designed to work seamlessly with shadcn/ui. Provides beautiful, responsive chart components. [PLANNED]",
            "advanced",
            Some("data-visualization"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            Some(vec!["recharts"]),
        ),
        create_ui_component_with_metadata(
            "data-table",
            "Powerful table and datagrids built using TanStack Table. Features sorting, filtering, pagination, and row selection with column resizing. [PLANNED]",
            "advanced",
            Some("data"),
            vec!["tailwind_fuse", "web-sys"],
            Some(vec!["table", "button", "checkbox", "input", "dropdown-menu"]),
            None,
            Some(vec!["@tanstack/react-table"]),
        ),
        create_ui_component_with_metadata(
            "sonner",
            "An opinionated toast component with beautiful animations. Supports multiple types, promises, and custom styling with stack management. [PLANNED]",
            "advanced",
            Some("notifications"),
            vec!["tailwind_fuse", "web-sys"],
            None,
            None,
            Some(vec!["sonner"]),
        ),
        create_ui_component_with_metadata(
            "typography",
            "Styles for headings, paragraphs, lists, and other text elements. Provides consistent typography with customizable variants and scales. [PLANNED]",
            "advanced",
            Some("text"),
            vec!["tailwind_fuse"],
            None,
            Some(create_css_vars(vec![
                ("--typography-h1", "2.5rem"),
                ("--typography-h2", "2rem"),
                ("--typography-h3", "1.75rem"),
                ("--typography-h4", "1.5rem"),
            ])),
            None,
        ),
    ]
}

pub static UI: LazyLock<HashMap<FrameworkName, Registry>> = LazyLock::new(|| {
    let complete_registry = create_complete_registry();
    let leptos_registry = create_leptos_registry();
    
    HashMap::from([
        (FrameworkName::Dioxus, complete_registry.clone()),
        (FrameworkName::Leptos, leptos_registry),
        // Yew framework removed - focusing on Leptos completion
    ])
});
